/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCaisseRouteImport } from './routes/_auth/caisse'
import { Route as AuthDevisRouteImport } from './routes/_auth/devis'
import { Route as AuthFacturesRouteImport } from './routes/_auth/factures'
import { Route as AuthFournisseursRouteImport } from './routes/_auth/fournisseurs'
import { Route as AuthParametresRouteImport } from './routes/_auth/parametres'
import { Route as AuthPromotionsRouteImport } from './routes/_auth/promotions'
import { Route as AuthRapportsRouteImport } from './routes/_auth/rapports'
import { Route as AuthStockRouteImport } from './routes/_auth/stock'
import { Route as AuthTransfertsRouteImport } from './routes/_auth/transferts'
import { Route as AuthVentesRouteImport } from './routes/_auth/ventes'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin.index'
import { Route as AuthAdminFacturationRouteImport } from './routes/_auth/admin.facturation'
import { Route as AuthAdminRolesRouteImport } from './routes/_auth/admin.roles'
import { Route as AuthAdminUtilisateursRouteImport } from './routes/_auth/admin.utilisateurs'
import { Route as AuthCatalogueIndexRouteImport } from './routes/_auth/catalogue.index'
import { Route as AuthCatalogueIdRouteImport } from './routes/_auth/catalogue.$id'
import { Route as AuthClientsIndexRouteImport } from './routes/_auth/clients.index'
import { Route as AuthClientsIdRouteImport } from './routes/_auth/clients.$id'
import { Route as AuthElectroniqueEcheanciersRouteImport } from './routes/_auth/electronique.echeanciers'
import { Route as AuthElectroniqueFichesRouteImport } from './routes/_auth/electronique.fiches'
import { Route as AuthElectroniqueGarantiesRouteImport } from './routes/_auth/electronique.garanties'
import { Route as AuthElectroniqueImeiRouteImport } from './routes/_auth/electronique.imei'
import { Route as AuthElectroniqueSavRouteImport } from './routes/_auth/electronique.sav'
import { Route as AuthFacturesIndexRouteImport } from './routes/_auth/factures.index'
import { Route as AuthFacturesIdRouteImport } from './routes/_auth/factures.$id'
import { Route as AuthFournisseursIndexRouteImport } from './routes/_auth/fournisseurs.index'
import { Route as AuthFournisseursIdRouteImport } from './routes/_auth/fournisseurs.$id'
import { Route as AuthPosIndexRouteImport } from './routes/_auth/pos.index'
import { Route as AuthPosOuvrirRouteImport } from './routes/_auth/pos.ouvrir'
import { Route as AuthVentesIndexRouteImport } from './routes/_auth/ventes.index'
import { Route as AuthVentesIdRouteImport } from './routes/_auth/ventes.$id'
import { Route as AuthElectroniqueEcheanciersIndexRouteImport } from './routes/_auth/electronique.echeanciers.index'
import { Route as AuthElectroniqueEcheanciersIdRouteImport } from './routes/_auth/electronique.echeanciers.$id'
import { Route as AuthElectroniqueFichesIndexRouteImport } from './routes/_auth/electronique.fiches.index'
import { Route as AuthElectroniqueFichesIdRouteImport } from './routes/_auth/electronique.fiches.$id'
import { Route as AuthElectroniqueSavIndexRouteImport } from './routes/_auth/electronique.sav.index'
import { Route as AuthElectroniqueSavIdRouteImport } from './routes/_auth/electronique.sav.$id'
import { Route as AuthFournisseursCommandesIdRouteImport } from './routes/_auth/fournisseurs.commandes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCaisseRoute = AuthCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDevisRoute = AuthDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFacturesRoute = AuthFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFournisseursRoute = AuthFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParametresRoute = AuthParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPromotionsRoute = AuthPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRapportsRoute = AuthRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStockRoute = AuthStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransfertsRoute = AuthTransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVentesRoute = AuthVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminFacturationRoute = AuthAdminFacturationRouteImport.update({
  id: '/admin/facturation',
  path: '/admin/facturation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRolesRoute = AuthAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUtilisateursRoute = AuthAdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCatalogueIndexRoute = AuthCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCatalogueIdRoute = AuthCatalogueIdRouteImport.update({
  id: '/catalogue/$id',
  path: '/catalogue/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsIndexRoute = AuthClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsIdRoute = AuthClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthElectroniqueEcheanciersRoute =
  AuthElectroniqueEcheanciersRouteImport.update({
    id: '/electronique/echeanciers',
    path: '/electronique/echeanciers',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthElectroniqueFichesRoute = AuthElectroniqueFichesRouteImport.update({
  id: '/electronique/fiches',
  path: '/electronique/fiches',
  getParentRoute: () => AuthRoute,
} as any)
const AuthElectroniqueGarantiesRoute =
  AuthElectroniqueGarantiesRouteImport.update({
    id: '/electronique/garanties',
    path: '/electronique/garanties',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthElectroniqueImeiRoute = AuthElectroniqueImeiRouteImport.update({
  id: '/electronique/imei',
  path: '/electronique/imei',
  getParentRoute: () => AuthRoute,
} as any)
const AuthElectroniqueSavRoute = AuthElectroniqueSavRouteImport.update({
  id: '/electronique/sav',
  path: '/electronique/sav',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFacturesIndexRoute = AuthFacturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFacturesRoute,
} as any)
const AuthFacturesIdRoute = AuthFacturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthFacturesRoute,
} as any)
const AuthFournisseursIndexRoute = AuthFournisseursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFournisseursRoute,
} as any)
const AuthFournisseursIdRoute = AuthFournisseursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthFournisseursRoute,
} as any)
const AuthPosIndexRoute = AuthPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPosOuvrirRoute = AuthPosOuvrirRouteImport.update({
  id: '/pos/ouvrir',
  path: '/pos/ouvrir',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVentesIndexRoute = AuthVentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthVentesRoute,
} as any)
const AuthVentesIdRoute = AuthVentesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthVentesRoute,
} as any)
const AuthElectroniqueEcheanciersIndexRoute =
  AuthElectroniqueEcheanciersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthElectroniqueEcheanciersRoute,
  } as any)
const AuthElectroniqueEcheanciersIdRoute =
  AuthElectroniqueEcheanciersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthElectroniqueEcheanciersRoute,
  } as any)
const AuthElectroniqueFichesIndexRoute =
  AuthElectroniqueFichesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthElectroniqueFichesRoute,
  } as any)
const AuthElectroniqueFichesIdRoute =
  AuthElectroniqueFichesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthElectroniqueFichesRoute,
  } as any)
const AuthElectroniqueSavIndexRoute =
  AuthElectroniqueSavIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthElectroniqueSavRoute,
  } as any)
const AuthElectroniqueSavIdRoute = AuthElectroniqueSavIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthElectroniqueSavRoute,
} as any)
const AuthFournisseursCommandesIdRoute =
  AuthFournisseursCommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => AuthFournisseursRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/connexion': typeof ConnexionRoute
  '/caisse': typeof AuthCaisseRoute
  '/devis': typeof AuthDevisRoute
  '/factures': typeof AuthFacturesRouteWithChildren
  '/fournisseurs': typeof AuthFournisseursRouteWithChildren
  '/parametres': typeof AuthParametresRoute
  '/promotions': typeof AuthPromotionsRoute
  '/rapports': typeof AuthRapportsRoute
  '/stock': typeof AuthStockRoute
  '/transferts': typeof AuthTransfertsRoute
  '/ventes': typeof AuthVentesRouteWithChildren
  '/admin/facturation': typeof AuthAdminFacturationRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/utilisateurs': typeof AuthAdminUtilisateursRoute
  '/catalogue/$id': typeof AuthCatalogueIdRoute
  '/clients/$id': typeof AuthClientsIdRoute
  '/electronique/echeanciers': typeof AuthElectroniqueEcheanciersRouteWithChildren
  '/electronique/fiches': typeof AuthElectroniqueFichesRouteWithChildren
  '/electronique/garanties': typeof AuthElectroniqueGarantiesRoute
  '/electronique/imei': typeof AuthElectroniqueImeiRoute
  '/electronique/sav': typeof AuthElectroniqueSavRouteWithChildren
  '/factures/$id': typeof AuthFacturesIdRoute
  '/fournisseurs/$id': typeof AuthFournisseursIdRoute
  '/pos/ouvrir': typeof AuthPosOuvrirRoute
  '/ventes/$id': typeof AuthVentesIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/catalogue/': typeof AuthCatalogueIndexRoute
  '/clients/': typeof AuthClientsIndexRoute
  '/factures/': typeof AuthFacturesIndexRoute
  '/fournisseurs/': typeof AuthFournisseursIndexRoute
  '/pos/': typeof AuthPosIndexRoute
  '/ventes/': typeof AuthVentesIndexRoute
  '/electronique/echeanciers/$id': typeof AuthElectroniqueEcheanciersIdRoute
  '/electronique/fiches/$id': typeof AuthElectroniqueFichesIdRoute
  '/electronique/sav/$id': typeof AuthElectroniqueSavIdRoute
  '/fournisseurs/commandes/$id': typeof AuthFournisseursCommandesIdRoute
  '/electronique/echeanciers/': typeof AuthElectroniqueEcheanciersIndexRoute
  '/electronique/fiches/': typeof AuthElectroniqueFichesIndexRoute
  '/electronique/sav/': typeof AuthElectroniqueSavIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/caisse': typeof AuthCaisseRoute
  '/devis': typeof AuthDevisRoute
  '/parametres': typeof AuthParametresRoute
  '/promotions': typeof AuthPromotionsRoute
  '/rapports': typeof AuthRapportsRoute
  '/stock': typeof AuthStockRoute
  '/transferts': typeof AuthTransfertsRoute
  '/': typeof AuthIndexRoute
  '/admin/facturation': typeof AuthAdminFacturationRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/utilisateurs': typeof AuthAdminUtilisateursRoute
  '/catalogue/$id': typeof AuthCatalogueIdRoute
  '/clients/$id': typeof AuthClientsIdRoute
  '/electronique/garanties': typeof AuthElectroniqueGarantiesRoute
  '/electronique/imei': typeof AuthElectroniqueImeiRoute
  '/factures/$id': typeof AuthFacturesIdRoute
  '/fournisseurs/$id': typeof AuthFournisseursIdRoute
  '/pos/ouvrir': typeof AuthPosOuvrirRoute
  '/ventes/$id': typeof AuthVentesIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/catalogue': typeof AuthCatalogueIndexRoute
  '/clients': typeof AuthClientsIndexRoute
  '/factures': typeof AuthFacturesIndexRoute
  '/fournisseurs': typeof AuthFournisseursIndexRoute
  '/pos': typeof AuthPosIndexRoute
  '/ventes': typeof AuthVentesIndexRoute
  '/electronique/echeanciers/$id': typeof AuthElectroniqueEcheanciersIdRoute
  '/electronique/fiches/$id': typeof AuthElectroniqueFichesIdRoute
  '/electronique/sav/$id': typeof AuthElectroniqueSavIdRoute
  '/fournisseurs/commandes/$id': typeof AuthFournisseursCommandesIdRoute
  '/electronique/echeanciers': typeof AuthElectroniqueEcheanciersIndexRoute
  '/electronique/fiches': typeof AuthElectroniqueFichesIndexRoute
  '/electronique/sav': typeof AuthElectroniqueSavIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_auth/caisse': typeof AuthCaisseRoute
  '/_auth/devis': typeof AuthDevisRoute
  '/_auth/factures': typeof AuthFacturesRouteWithChildren
  '/_auth/fournisseurs': typeof AuthFournisseursRouteWithChildren
  '/_auth/parametres': typeof AuthParametresRoute
  '/_auth/promotions': typeof AuthPromotionsRoute
  '/_auth/rapports': typeof AuthRapportsRoute
  '/_auth/stock': typeof AuthStockRoute
  '/_auth/transferts': typeof AuthTransfertsRoute
  '/_auth/ventes': typeof AuthVentesRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/facturation': typeof AuthAdminFacturationRoute
  '/_auth/admin/roles': typeof AuthAdminRolesRoute
  '/_auth/admin/utilisateurs': typeof AuthAdminUtilisateursRoute
  '/_auth/catalogue/$id': typeof AuthCatalogueIdRoute
  '/_auth/clients/$id': typeof AuthClientsIdRoute
  '/_auth/electronique/echeanciers': typeof AuthElectroniqueEcheanciersRouteWithChildren
  '/_auth/electronique/fiches': typeof AuthElectroniqueFichesRouteWithChildren
  '/_auth/electronique/garanties': typeof AuthElectroniqueGarantiesRoute
  '/_auth/electronique/imei': typeof AuthElectroniqueImeiRoute
  '/_auth/electronique/sav': typeof AuthElectroniqueSavRouteWithChildren
  '/_auth/factures/$id': typeof AuthFacturesIdRoute
  '/_auth/fournisseurs/$id': typeof AuthFournisseursIdRoute
  '/_auth/pos/ouvrir': typeof AuthPosOuvrirRoute
  '/_auth/ventes/$id': typeof AuthVentesIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/catalogue/': typeof AuthCatalogueIndexRoute
  '/_auth/clients/': typeof AuthClientsIndexRoute
  '/_auth/factures/': typeof AuthFacturesIndexRoute
  '/_auth/fournisseurs/': typeof AuthFournisseursIndexRoute
  '/_auth/pos/': typeof AuthPosIndexRoute
  '/_auth/ventes/': typeof AuthVentesIndexRoute
  '/_auth/electronique/echeanciers/$id': typeof AuthElectroniqueEcheanciersIdRoute
  '/_auth/electronique/fiches/$id': typeof AuthElectroniqueFichesIdRoute
  '/_auth/electronique/sav/$id': typeof AuthElectroniqueSavIdRoute
  '/_auth/fournisseurs/commandes/$id': typeof AuthFournisseursCommandesIdRoute
  '/_auth/electronique/echeanciers/': typeof AuthElectroniqueEcheanciersIndexRoute
  '/_auth/electronique/fiches/': typeof AuthElectroniqueFichesIndexRoute
  '/_auth/electronique/sav/': typeof AuthElectroniqueSavIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/caisse'
    | '/devis'
    | '/factures'
    | '/fournisseurs'
    | '/parametres'
    | '/promotions'
    | '/rapports'
    | '/stock'
    | '/transferts'
    | '/ventes'
    | '/admin/facturation'
    | '/admin/roles'
    | '/admin/utilisateurs'
    | '/catalogue/$id'
    | '/clients/$id'
    | '/electronique/echeanciers'
    | '/electronique/fiches'
    | '/electronique/garanties'
    | '/electronique/imei'
    | '/electronique/sav'
    | '/factures/$id'
    | '/fournisseurs/$id'
    | '/pos/ouvrir'
    | '/ventes/$id'
    | '/admin/'
    | '/catalogue/'
    | '/clients/'
    | '/factures/'
    | '/fournisseurs/'
    | '/pos/'
    | '/ventes/'
    | '/electronique/echeanciers/$id'
    | '/electronique/fiches/$id'
    | '/electronique/sav/$id'
    | '/fournisseurs/commandes/$id'
    | '/electronique/echeanciers/'
    | '/electronique/fiches/'
    | '/electronique/sav/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/caisse'
    | '/devis'
    | '/parametres'
    | '/promotions'
    | '/rapports'
    | '/stock'
    | '/transferts'
    | '/'
    | '/admin/facturation'
    | '/admin/roles'
    | '/admin/utilisateurs'
    | '/catalogue/$id'
    | '/clients/$id'
    | '/electronique/garanties'
    | '/electronique/imei'
    | '/factures/$id'
    | '/fournisseurs/$id'
    | '/pos/ouvrir'
    | '/ventes/$id'
    | '/admin'
    | '/catalogue'
    | '/clients'
    | '/factures'
    | '/fournisseurs'
    | '/pos'
    | '/ventes'
    | '/electronique/echeanciers/$id'
    | '/electronique/fiches/$id'
    | '/electronique/sav/$id'
    | '/fournisseurs/commandes/$id'
    | '/electronique/echeanciers'
    | '/electronique/fiches'
    | '/electronique/sav'
  id:
    | '__root__'
    | '/_auth'
    | '/connexion'
    | '/_auth/caisse'
    | '/_auth/devis'
    | '/_auth/factures'
    | '/_auth/fournisseurs'
    | '/_auth/parametres'
    | '/_auth/promotions'
    | '/_auth/rapports'
    | '/_auth/stock'
    | '/_auth/transferts'
    | '/_auth/ventes'
    | '/_auth/'
    | '/_auth/admin/facturation'
    | '/_auth/admin/roles'
    | '/_auth/admin/utilisateurs'
    | '/_auth/catalogue/$id'
    | '/_auth/clients/$id'
    | '/_auth/electronique/echeanciers'
    | '/_auth/electronique/fiches'
    | '/_auth/electronique/garanties'
    | '/_auth/electronique/imei'
    | '/_auth/electronique/sav'
    | '/_auth/factures/$id'
    | '/_auth/fournisseurs/$id'
    | '/_auth/pos/ouvrir'
    | '/_auth/ventes/$id'
    | '/_auth/admin/'
    | '/_auth/catalogue/'
    | '/_auth/clients/'
    | '/_auth/factures/'
    | '/_auth/fournisseurs/'
    | '/_auth/pos/'
    | '/_auth/ventes/'
    | '/_auth/electronique/echeanciers/$id'
    | '/_auth/electronique/fiches/$id'
    | '/_auth/electronique/sav/$id'
    | '/_auth/fournisseurs/commandes/$id'
    | '/_auth/electronique/echeanciers/'
    | '/_auth/electronique/fiches/'
    | '/_auth/electronique/sav/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/caisse': {
      id: '/_auth/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AuthCaisseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/devis': {
      id: '/_auth/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthDevisRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/factures': {
      id: '/_auth/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthFacturesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fournisseurs': {
      id: '/_auth/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthFournisseursRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/parametres': {
      id: '/_auth/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthParametresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/promotions': {
      id: '/_auth/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthPromotionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rapports': {
      id: '/_auth/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthRapportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stock': {
      id: '/_auth/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthStockRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transferts': {
      id: '/_auth/transferts'
      path: '/transferts'
      fullPath: '/transferts'
      preLoaderRoute: typeof AuthTransfertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ventes': {
      id: '/_auth/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthVentesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/facturation': {
      id: '/_auth/admin/facturation'
      path: '/admin/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AuthAdminFacturationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/roles': {
      id: '/_auth/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthAdminRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/utilisateurs': {
      id: '/_auth/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthAdminUtilisateursRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/catalogue/': {
      id: '/_auth/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof AuthCatalogueIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/catalogue/$id': {
      id: '/_auth/catalogue/$id'
      path: '/catalogue/$id'
      fullPath: '/catalogue/$id'
      preLoaderRoute: typeof AuthCatalogueIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/': {
      id: '/_auth/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthClientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/$id': {
      id: '/_auth/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthClientsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/electronique/echeanciers': {
      id: '/_auth/electronique/echeanciers'
      path: '/electronique/echeanciers'
      fullPath: '/electronique/echeanciers'
      preLoaderRoute: typeof AuthElectroniqueEcheanciersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/electronique/fiches': {
      id: '/_auth/electronique/fiches'
      path: '/electronique/fiches'
      fullPath: '/electronique/fiches'
      preLoaderRoute: typeof AuthElectroniqueFichesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/electronique/garanties': {
      id: '/_auth/electronique/garanties'
      path: '/electronique/garanties'
      fullPath: '/electronique/garanties'
      preLoaderRoute: typeof AuthElectroniqueGarantiesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/electronique/imei': {
      id: '/_auth/electronique/imei'
      path: '/electronique/imei'
      fullPath: '/electronique/imei'
      preLoaderRoute: typeof AuthElectroniqueImeiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/electronique/sav': {
      id: '/_auth/electronique/sav'
      path: '/electronique/sav'
      fullPath: '/electronique/sav'
      preLoaderRoute: typeof AuthElectroniqueSavRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/factures/': {
      id: '/_auth/factures/'
      path: '/'
      fullPath: '/factures/'
      preLoaderRoute: typeof AuthFacturesIndexRouteImport
      parentRoute: typeof AuthFacturesRoute
    }
    '/_auth/factures/$id': {
      id: '/_auth/factures/$id'
      path: '/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof AuthFacturesIdRouteImport
      parentRoute: typeof AuthFacturesRoute
    }
    '/_auth/fournisseurs/': {
      id: '/_auth/fournisseurs/'
      path: '/'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof AuthFournisseursIndexRouteImport
      parentRoute: typeof AuthFournisseursRoute
    }
    '/_auth/fournisseurs/$id': {
      id: '/_auth/fournisseurs/$id'
      path: '/$id'
      fullPath: '/fournisseurs/$id'
      preLoaderRoute: typeof AuthFournisseursIdRouteImport
      parentRoute: typeof AuthFournisseursRoute
    }
    '/_auth/pos/': {
      id: '/_auth/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AuthPosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pos/ouvrir': {
      id: '/_auth/pos/ouvrir'
      path: '/pos/ouvrir'
      fullPath: '/pos/ouvrir'
      preLoaderRoute: typeof AuthPosOuvrirRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ventes/': {
      id: '/_auth/ventes/'
      path: '/'
      fullPath: '/ventes/'
      preLoaderRoute: typeof AuthVentesIndexRouteImport
      parentRoute: typeof AuthVentesRoute
    }
    '/_auth/ventes/$id': {
      id: '/_auth/ventes/$id'
      path: '/$id'
      fullPath: '/ventes/$id'
      preLoaderRoute: typeof AuthVentesIdRouteImport
      parentRoute: typeof AuthVentesRoute
    }
    '/_auth/electronique/echeanciers/': {
      id: '/_auth/electronique/echeanciers/'
      path: '/'
      fullPath: '/electronique/echeanciers/'
      preLoaderRoute: typeof AuthElectroniqueEcheanciersIndexRouteImport
      parentRoute: typeof AuthElectroniqueEcheanciersRoute
    }
    '/_auth/electronique/echeanciers/$id': {
      id: '/_auth/electronique/echeanciers/$id'
      path: '/$id'
      fullPath: '/electronique/echeanciers/$id'
      preLoaderRoute: typeof AuthElectroniqueEcheanciersIdRouteImport
      parentRoute: typeof AuthElectroniqueEcheanciersRoute
    }
    '/_auth/electronique/fiches/': {
      id: '/_auth/electronique/fiches/'
      path: '/'
      fullPath: '/electronique/fiches/'
      preLoaderRoute: typeof AuthElectroniqueFichesIndexRouteImport
      parentRoute: typeof AuthElectroniqueFichesRoute
    }
    '/_auth/electronique/fiches/$id': {
      id: '/_auth/electronique/fiches/$id'
      path: '/$id'
      fullPath: '/electronique/fiches/$id'
      preLoaderRoute: typeof AuthElectroniqueFichesIdRouteImport
      parentRoute: typeof AuthElectroniqueFichesRoute
    }
    '/_auth/electronique/sav/': {
      id: '/_auth/electronique/sav/'
      path: '/'
      fullPath: '/electronique/sav/'
      preLoaderRoute: typeof AuthElectroniqueSavIndexRouteImport
      parentRoute: typeof AuthElectroniqueSavRoute
    }
    '/_auth/electronique/sav/$id': {
      id: '/_auth/electronique/sav/$id'
      path: '/$id'
      fullPath: '/electronique/sav/$id'
      preLoaderRoute: typeof AuthElectroniqueSavIdRouteImport
      parentRoute: typeof AuthElectroniqueSavRoute
    }
    '/_auth/fournisseurs/commandes/$id': {
      id: '/_auth/fournisseurs/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/fournisseurs/commandes/$id'
      preLoaderRoute: typeof AuthFournisseursCommandesIdRouteImport
      parentRoute: typeof AuthFournisseursRoute
    }
  }
}

interface AuthFacturesRouteChildren {
  AuthFacturesIdRoute: typeof AuthFacturesIdRoute
  AuthFacturesIndexRoute: typeof AuthFacturesIndexRoute
}

const AuthFacturesRouteChildren: AuthFacturesRouteChildren = {
  AuthFacturesIdRoute: AuthFacturesIdRoute,
  AuthFacturesIndexRoute: AuthFacturesIndexRoute,
}

const AuthFacturesRouteWithChildren = AuthFacturesRoute._addFileChildren(
  AuthFacturesRouteChildren,
)

interface AuthFournisseursRouteChildren {
  AuthFournisseursIdRoute: typeof AuthFournisseursIdRoute
  AuthFournisseursIndexRoute: typeof AuthFournisseursIndexRoute
  AuthFournisseursCommandesIdRoute: typeof AuthFournisseursCommandesIdRoute
}

const AuthFournisseursRouteChildren: AuthFournisseursRouteChildren = {
  AuthFournisseursIdRoute: AuthFournisseursIdRoute,
  AuthFournisseursIndexRoute: AuthFournisseursIndexRoute,
  AuthFournisseursCommandesIdRoute: AuthFournisseursCommandesIdRoute,
}

const AuthFournisseursRouteWithChildren =
  AuthFournisseursRoute._addFileChildren(AuthFournisseursRouteChildren)

interface AuthVentesRouteChildren {
  AuthVentesIdRoute: typeof AuthVentesIdRoute
  AuthVentesIndexRoute: typeof AuthVentesIndexRoute
}

const AuthVentesRouteChildren: AuthVentesRouteChildren = {
  AuthVentesIdRoute: AuthVentesIdRoute,
  AuthVentesIndexRoute: AuthVentesIndexRoute,
}

const AuthVentesRouteWithChildren = AuthVentesRoute._addFileChildren(
  AuthVentesRouteChildren,
)

interface AuthElectroniqueEcheanciersRouteChildren {
  AuthElectroniqueEcheanciersIdRoute: typeof AuthElectroniqueEcheanciersIdRoute
  AuthElectroniqueEcheanciersIndexRoute: typeof AuthElectroniqueEcheanciersIndexRoute
}

const AuthElectroniqueEcheanciersRouteChildren: AuthElectroniqueEcheanciersRouteChildren =
  {
    AuthElectroniqueEcheanciersIdRoute: AuthElectroniqueEcheanciersIdRoute,
    AuthElectroniqueEcheanciersIndexRoute:
      AuthElectroniqueEcheanciersIndexRoute,
  }

const AuthElectroniqueEcheanciersRouteWithChildren =
  AuthElectroniqueEcheanciersRoute._addFileChildren(
    AuthElectroniqueEcheanciersRouteChildren,
  )

interface AuthElectroniqueFichesRouteChildren {
  AuthElectroniqueFichesIdRoute: typeof AuthElectroniqueFichesIdRoute
  AuthElectroniqueFichesIndexRoute: typeof AuthElectroniqueFichesIndexRoute
}

const AuthElectroniqueFichesRouteChildren: AuthElectroniqueFichesRouteChildren =
  {
    AuthElectroniqueFichesIdRoute: AuthElectroniqueFichesIdRoute,
    AuthElectroniqueFichesIndexRoute: AuthElectroniqueFichesIndexRoute,
  }

const AuthElectroniqueFichesRouteWithChildren =
  AuthElectroniqueFichesRoute._addFileChildren(
    AuthElectroniqueFichesRouteChildren,
  )

interface AuthElectroniqueSavRouteChildren {
  AuthElectroniqueSavIdRoute: typeof AuthElectroniqueSavIdRoute
  AuthElectroniqueSavIndexRoute: typeof AuthElectroniqueSavIndexRoute
}

const AuthElectroniqueSavRouteChildren: AuthElectroniqueSavRouteChildren = {
  AuthElectroniqueSavIdRoute: AuthElectroniqueSavIdRoute,
  AuthElectroniqueSavIndexRoute: AuthElectroniqueSavIndexRoute,
}

const AuthElectroniqueSavRouteWithChildren =
  AuthElectroniqueSavRoute._addFileChildren(AuthElectroniqueSavRouteChildren)

interface AuthRouteChildren {
  AuthCaisseRoute: typeof AuthCaisseRoute
  AuthDevisRoute: typeof AuthDevisRoute
  AuthFacturesRoute: typeof AuthFacturesRouteWithChildren
  AuthFournisseursRoute: typeof AuthFournisseursRouteWithChildren
  AuthParametresRoute: typeof AuthParametresRoute
  AuthPromotionsRoute: typeof AuthPromotionsRoute
  AuthRapportsRoute: typeof AuthRapportsRoute
  AuthStockRoute: typeof AuthStockRoute
  AuthTransfertsRoute: typeof AuthTransfertsRoute
  AuthVentesRoute: typeof AuthVentesRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminFacturationRoute: typeof AuthAdminFacturationRoute
  AuthAdminRolesRoute: typeof AuthAdminRolesRoute
  AuthAdminUtilisateursRoute: typeof AuthAdminUtilisateursRoute
  AuthCatalogueIdRoute: typeof AuthCatalogueIdRoute
  AuthClientsIdRoute: typeof AuthClientsIdRoute
  AuthElectroniqueEcheanciersRoute: typeof AuthElectroniqueEcheanciersRouteWithChildren
  AuthElectroniqueFichesRoute: typeof AuthElectroniqueFichesRouteWithChildren
  AuthElectroniqueGarantiesRoute: typeof AuthElectroniqueGarantiesRoute
  AuthElectroniqueImeiRoute: typeof AuthElectroniqueImeiRoute
  AuthElectroniqueSavRoute: typeof AuthElectroniqueSavRouteWithChildren
  AuthPosOuvrirRoute: typeof AuthPosOuvrirRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthCatalogueIndexRoute: typeof AuthCatalogueIndexRoute
  AuthClientsIndexRoute: typeof AuthClientsIndexRoute
  AuthPosIndexRoute: typeof AuthPosIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCaisseRoute: AuthCaisseRoute,
  AuthDevisRoute: AuthDevisRoute,
  AuthFacturesRoute: AuthFacturesRouteWithChildren,
  AuthFournisseursRoute: AuthFournisseursRouteWithChildren,
  AuthParametresRoute: AuthParametresRoute,
  AuthPromotionsRoute: AuthPromotionsRoute,
  AuthRapportsRoute: AuthRapportsRoute,
  AuthStockRoute: AuthStockRoute,
  AuthTransfertsRoute: AuthTransfertsRoute,
  AuthVentesRoute: AuthVentesRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminFacturationRoute: AuthAdminFacturationRoute,
  AuthAdminRolesRoute: AuthAdminRolesRoute,
  AuthAdminUtilisateursRoute: AuthAdminUtilisateursRoute,
  AuthCatalogueIdRoute: AuthCatalogueIdRoute,
  AuthClientsIdRoute: AuthClientsIdRoute,
  AuthElectroniqueEcheanciersRoute:
    AuthElectroniqueEcheanciersRouteWithChildren,
  AuthElectroniqueFichesRoute: AuthElectroniqueFichesRouteWithChildren,
  AuthElectroniqueGarantiesRoute: AuthElectroniqueGarantiesRoute,
  AuthElectroniqueImeiRoute: AuthElectroniqueImeiRoute,
  AuthElectroniqueSavRoute: AuthElectroniqueSavRouteWithChildren,
  AuthPosOuvrirRoute: AuthPosOuvrirRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthCatalogueIndexRoute: AuthCatalogueIndexRoute,
  AuthClientsIndexRoute: AuthClientsIndexRoute,
  AuthPosIndexRoute: AuthPosIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
